# This pipeline is used to deploy Policies, Initiative definitions and Assignments into Azure.
name: EPAC Dev Workflow

on:
  push:
    branches:
      - feature/**
    paths:
      - "Definitions/**"
      - ".github/**"
  workflow_dispatch:
    inputs:
      triggered-by:
        description: 'Who triggered this workflow'
        required: false
        default: 'manual'
      pr-number:
        description: 'PR number if triggered by policy sync'
        required: false
      branch-name:
        description: 'Branch name if triggered by policy sync'
        required: false
      trigger-reason:
        description: 'Reason for triggering'
        required: false
        default: 'Manual trigger'

env:
  PAC_OUTPUT_FOLDER: ./Output
  PAC_DEFINITIONS_FOLDER: ./Definitions

permissions:
  contents: read
  id-token: write

jobs:
  plan:
    name: Plan epac-dev
    uses: ./.github/workflows/plan.yml
    with:
      pacEnvironmentSelector: epac-dev
      planGitHubEnvironment: EPAC-DEV
      PAC_OUTPUT_FOLDER: ./Output
      PAC_DEFINITIONS_FOLDER: ./Definitions
    secrets: inherit

  deployPolicy:
    name: Deploy epac-dev Policy Changes
    needs: plan
    if: needs.plan.outputs.deployPolicyChanges == 'yes'
    uses: ./.github/workflows/deploy-policy.yml
    with:
      pacEnvironmentSelector: epac-dev
      planGitHubEnvironment: EPAC-DEV
      PAC_INPUT_FOLDER: ./Output
      PAC_DEFINITIONS_FOLDER: ./Definitions
    secrets: inherit

  deployRoles:
    name: Deploy epac-dev Role Changes
    needs: plan
    if: needs.plan.outputs.deployRoleChanges == 'yes'
    uses: ./.github/workflows/deploy-roles.yml
    with:
      pacEnvironmentSelector: epac-dev
      planGitHubEnvironment: EPAC-DEV
      PAC_INPUT_FOLDER: ./Output
      PAC_DEFINITIONS_FOLDER: ./Definitions
    secrets: inherit

  tenantPlan:
    name: Plan tenant
    needs: [deployPolicy, deployRoles]
    if: |
      always()
      && !contains(needs.*.result,'failure')
    uses: ./.github/workflows/plan.yml
    with:
      pacEnvironmentSelector: tenant
      planGitHubEnvironment: TENANT-PLAN
      PAC_OUTPUT_FOLDER: ./Output
      PAC_DEFINITIONS_FOLDER: ./Definitions
    secrets: inherit
